/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.planificadores;

import java.awt.*;
import java.util.HashSet;
import java.util.Set;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import java.util.LinkedList;

/**
 *
 * @author Ricardo Guardiola
 */
public class SPF extends javax.swing.JFrame {

    DefaultTableModel model;
    DefaultTableModel model2;
    int i = 0;
    int j = 0;
    int k = 0;
    LinkedList llName = new LinkedList();
    LinkedList llSize = new LinkedList();

    /**
     * Creates new form FIFO
     */
    public SPF() {

        initComponents();
        model = new DefaultTableModel();
        model2 = new DefaultTableModel();
        jTable1.setModel(model);
        jTable2.setModel(model2);
        model.addColumn("Name of Process");
        model.addColumn("Size of Process");
        model2.addColumn("Process");

    }

    public void ClearAll() {
        txtName.setText("");
        txtSize.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMemory = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnLoad = new javax.swing.JButton();
        Execute = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Execute1 = new javax.swing.JButton();
        lblName1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblName3 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        lblName5 = new javax.swing.JLabel();
        lblName6 = new javax.swing.JLabel();
        lblName7 = new javax.swing.JLabel();
        lblName8 = new javax.swing.JLabel();
        lblName9 = new javax.swing.JLabel();
        lblName10 = new javax.swing.JLabel();
        lblName11 = new javax.swing.JLabel();
        lblName12 = new javax.swing.JLabel();
        lblName13 = new javax.swing.JLabel();
        lblName14 = new javax.swing.JLabel();
        lblName15 = new javax.swing.JLabel();
        lblName16 = new javax.swing.JLabel();
        lblName17 = new javax.swing.JLabel();
        lblName18 = new javax.swing.JLabel();
        lblName19 = new javax.swing.JLabel();
        lblName20 = new javax.swing.JLabel();
        lblTamanio1 = new javax.swing.JLabel();
        lblTamanio2 = new javax.swing.JLabel();
        lblTamanio3 = new javax.swing.JLabel();
        lblTamanio4 = new javax.swing.JLabel();
        lblTamanio5 = new javax.swing.JLabel();
        lblTamanio6 = new javax.swing.JLabel();
        lblTamanio7 = new javax.swing.JLabel();
        lblTamanio8 = new javax.swing.JLabel();
        lblTamanio9 = new javax.swing.JLabel();
        lblTamanio10 = new javax.swing.JLabel();
        lblTamanio11 = new javax.swing.JLabel();
        lblTamanio12 = new javax.swing.JLabel();
        lblTamanio13 = new javax.swing.JLabel();
        lblTamanio14 = new javax.swing.JLabel();
        lblTamanio15 = new javax.swing.JLabel();
        lblTamanio16 = new javax.swing.JLabel();
        lblTamanio17 = new javax.swing.JLabel();
        lblTamanio18 = new javax.swing.JLabel();
        lblTamanio19 = new javax.swing.JLabel();
        lblTamanio20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setText("SPF: Primero el proceso más corto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 53));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 647, 10));

        txtName.setText("A");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 70, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 70, -1));

        jLabel2.setText("Set the name for the process");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtSize.setText("5");
        getContentPane().add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 71, -1));

        jLabel3.setText("Set the size for the process");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtMemory.setText("10");
        getContentPane().add(txtMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 71, -1));

        jLabel4.setText("Set the size of the memory");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 620, 30));

        jLabel5.setText("Prepared Process");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 290, 170));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Process", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 730, 300));

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        Execute.setText("Execute");
        Execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteActionPerformed(evt);
            }
        });
        getContentPane().add(Execute, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jButton1.setText("Return to main menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        Execute1.setText("Load into memory");
        Execute1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Execute1ActionPerformed(evt);
            }
        });
        getContentPane().add(Execute1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        lblName1.setText("jLabel6");
        getContentPane().add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        lblName2.setText("jLabel6");
        getContentPane().add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        lblName3.setText("jLabel6");
        getContentPane().add(lblName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, -1, -1));

        lblName4.setText("jLabel6");
        getContentPane().add(lblName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, -1, -1));

        lblName5.setText("jLabel6");
        getContentPane().add(lblName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, -1, -1));

        lblName6.setText("jLabel6");
        getContentPane().add(lblName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, -1, -1));

        lblName7.setText("jLabel6");
        getContentPane().add(lblName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, -1, -1));

        lblName8.setText("jLabel6");
        getContentPane().add(lblName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        lblName9.setText("jLabel6");
        getContentPane().add(lblName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, -1));

        lblName10.setText("jLabel6");
        getContentPane().add(lblName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, -1, -1));

        lblName11.setText("jLabel6");
        getContentPane().add(lblName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, -1, -1));

        lblName12.setText("jLabel6");
        getContentPane().add(lblName12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, -1, -1));

        lblName13.setText("jLabel6");
        getContentPane().add(lblName13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, -1, -1));

        lblName14.setText("jLabel6");
        getContentPane().add(lblName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, -1, -1));

        lblName15.setText("jLabel6");
        getContentPane().add(lblName15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, -1, -1));

        lblName16.setText("jLabel6");
        getContentPane().add(lblName16, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, -1, -1));

        lblName17.setText("jLabel6");
        getContentPane().add(lblName17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, -1));

        lblName18.setText("jLabel6");
        getContentPane().add(lblName18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, -1, -1));

        lblName19.setText("jLabel6");
        getContentPane().add(lblName19, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 480, -1, -1));

        lblName20.setText("jLabel6");
        getContentPane().add(lblName20, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, -1, -1));
        getContentPane().add(lblTamanio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 50, 20));
        getContentPane().add(lblTamanio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 50, 20));
        getContentPane().add(lblTamanio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 50, 20));
        getContentPane().add(lblTamanio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 50, 20));
        getContentPane().add(lblTamanio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 50, 20));
        getContentPane().add(lblTamanio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 50, 20));
        getContentPane().add(lblTamanio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 50, 20));
        getContentPane().add(lblTamanio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 50, 20));
        getContentPane().add(lblTamanio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 50, 20));
        getContentPane().add(lblTamanio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 50, 20));
        getContentPane().add(lblTamanio11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 50, 20));
        getContentPane().add(lblTamanio12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 50, 20));
        getContentPane().add(lblTamanio13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 50, 20));
        getContentPane().add(lblTamanio14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 50, 20));
        getContentPane().add(lblTamanio15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 50, 20));
        getContentPane().add(lblTamanio16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 50, 20));
        getContentPane().add(lblTamanio17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 50, 20));
        getContentPane().add(lblTamanio18, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 50, 20));
        getContentPane().add(lblTamanio19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 50, 20));
        getContentPane().add(lblTamanio20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 50, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (lblTamanio1.getText() == "") {
            lblTamanio1.setText(txtSize.getText());
            lblName1.setText(txtName.getText());

        } else if (lblTamanio2.getText() == "") {
            lblTamanio2.setText(txtSize.getText());
            lblName2.setText(txtName.getText());

        } else if (lblTamanio3.getText() == "") {
            lblTamanio3.setText(txtSize.getText());
            lblName3.setText(txtName.getText());

        } else if (lblTamanio4.getText() == "") {
            lblTamanio4.setText(txtSize.getText());
            lblName4.setText(txtName.getText());

        } else if (lblTamanio5.getText() == "") {
            lblTamanio5.setText(txtSize.getText());
            lblName5.setText(txtName.getText());

        } else if (lblTamanio6.getText() == "") {
            lblTamanio6.setText(txtSize.getText());
            lblName6.setText(txtName.getText());

        } else if (lblTamanio7.getText() == "") {
            lblTamanio7.setText(txtSize.getText());
            lblName7.setText(txtName.getText());

        } else if (lblTamanio8.getText() == "") {
            lblTamanio8.setText(txtSize.getText());
            lblName8.setText(txtName.getText());

        } else if (lblTamanio9.getText() == "") {
            lblTamanio9.setText(txtSize.getText());
            lblName9.setText(txtName.getText());

        } else if (lblTamanio10.getText() == "") {
            lblTamanio10.setText(txtSize.getText());
            lblName10.setText(txtName.getText());

        } else if (lblTamanio11.getText() == "") {
            lblTamanio11.setText(txtSize.getText());
            lblName11.setText(txtName.getText());

        } else if (lblTamanio12.getText() == "") {
            lblTamanio12.setText(txtSize.getText());
            lblName12.setText(txtName.getText());

        } else if (lblTamanio13.getText() == "") {
            lblTamanio13.setText(txtSize.getText());
            lblName13.setText(txtName.getText());

        } else if (lblTamanio14.getText() == "") {
            lblTamanio14.setText(txtSize.getText());
            lblName14.setText(txtName.getText());

        } else if (lblTamanio15.getText() == "") {
            lblTamanio15.setText(txtSize.getText());
            lblName15.setText(txtName.getText());

        } else if (lblTamanio16.getText() == "") {
            lblTamanio16.setText(txtSize.getText());
            lblName16.setText(txtName.getText());

        } else if (lblTamanio17.getText() == "") {
            lblTamanio17.setText(txtSize.getText());
            lblName17.setText(txtName.getText());

        } else if (lblTamanio18.getText() == "") {
            lblTamanio18.setText(txtSize.getText());
            lblName18.setText(txtName.getText());

        } else if (lblTamanio19.getText() == "") {
            lblTamanio19.setText(txtSize.getText());
            lblName19.setText(txtName.getText());

        } else if (lblTamanio20.getText() == "") {
            lblTamanio20.setText(txtSize.getText());
            lblName20.setText(txtName.getText());
        }

        if (lblTamanio1.getText() == "") {
            model.addRow(new Object[]{
                lblName1.getText(),
                lblTamanio1.getText()
            });
        }
        llName.addLast(lblName1.getText());
        llSize.addLast(Integer.parseInt(lblTamanio1.getText()));

        if (Integer.parseInt(lblTamanio2.getText()) < Integer.parseInt(lblTamanio3.getText())) {
            if (Integer.parseInt(lblTamanio2.getText()) < Integer.parseInt(lblTamanio4.getText())) {
                if (Integer.parseInt(lblTamanio2.getText()) < Integer.parseInt(lblTamanio5.getText())) {
                    if (Integer.parseInt(lblTamanio2.getText()) < Integer.parseInt(lblTamanio6.getText())) {
                        if (Integer.parseInt(lblTamanio2.getText()) < Integer.parseInt(lblTamanio7.getText())) {
                            if (Integer.parseInt(lblTamanio2.getText()) < Integer.parseInt(lblTamanio8.getText())) {
                                if (Integer.parseInt(lblTamanio2.getText()) < Integer.parseInt(lblTamanio9.getText())) {
                                    if (Integer.parseInt(lblTamanio2.getText()) < Integer.parseInt(lblTamanio10.getText())) {
                                        if (Integer.parseInt(lblTamanio1.getText()) >= 1) {
                                            model.addRow(new Object[]{
                                                lblName1.getText(),
                                                lblTamanio1.getText()
                                            });
                                            llName.addLast(lblName1.getText());
                                            llSize.addLast(Integer.parseInt(lblTamanio1.getText()));
                                        } else {
                                            JOptionPane.showMessageDialog(null,
                                                    "Process Size invalid", "Error",
                                                    JOptionPane.ERROR_MESSAGE);
                                        }
                                        if (Integer.parseInt(lblTamanio3.getText()) < Integer.parseInt(lblTamanio4.getText())) {
                                            if (Integer.parseInt(lblTamanio3.getText()) < Integer.parseInt(lblTamanio5.getText())) {
                                                if (Integer.parseInt(lblTamanio3.getText()) < Integer.parseInt(lblTamanio6.getText())) {
                                                    if (Integer.parseInt(lblTamanio3.getText()) < Integer.parseInt(lblTamanio7.getText())) {
                                                        if (Integer.parseInt(lblTamanio3.getText()) < Integer.parseInt(lblTamanio8.getText())) {
                                                            if (Integer.parseInt(lblTamanio3.getText()) < Integer.parseInt(lblTamanio9.getText())) {
                                                                if (Integer.parseInt(lblTamanio3.getText()) < Integer.parseInt(lblTamanio10.getText())) {
                                                                    if (Integer.parseInt(lblTamanio3.getText()) >= 1) {
                                                                        model.addRow(new Object[]{
                                                                            lblName1.getText(),
                                                                            lblTamanio1.getText()
                                                                        });
                                                                        llName.addLast(lblName1.getText());
                                                                        llSize.addLast(Integer.parseInt(lblTamanio1.getText()));
                                                                    } else {
                                                                        JOptionPane.showMessageDialog(null,
                                                                                "Process Size invalid", "Error",
                                                                                JOptionPane.ERROR_MESSAGE);
                                                                    }

                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        /*if (Integer.parseInt(txtSize.getText()) >= 1) {
            model.addRow(new Object[]{
                txtName.getText(),
                txtSize.getText()
            });
            llName.addLast(txtName.getText());
            llSize.addLast(Integer.parseInt(txtSize.getText()));
//        this.ClearAll();
        } else {
            JOptionPane.showMessageDialog(null,
                    "Process Size invalid", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }*/

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        i = Integer.parseInt(txtMemory.getText());
        while (j < i) {
            model2.addColumn(j + 1);
//            System.out.println(i);

            j++;
        }
        try {
//            model2.addRow(model.getDataVector().firstElement());
//              model2.addRow(llName.toArray());

//            model2.addRow(new Object[]{            });
        } catch (Exception e) {
            e.printStackTrace();
        }
//        model2.addColumn(i);
//        model2.addRow(model.getDataVector());


    }//GEN-LAST:event_btnLoadActionPerformed

    private void ExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecuteActionPerformed

        j = 0;
        i = 0;
        k = 0;

        while (j < model2.getRowCount()) {
            while (i < Integer.parseInt(llSize.getFirst().toString())) {
                model2.setValueAt(llSize.getFirst(), j, i + 1 + k);
                i++;
            }
            llSize.pop();
            k += i;
            j++;
            i = 0;
        }


    }//GEN-LAST:event_ExecuteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Execute1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Execute1ActionPerformed
        // TODO add your handling code here:
        System.out.println(llName.getFirst());
        System.out.println(llSize.getFirst());
        j = 1;
        model2.addRow(new Object[]{
            llName.getFirst()
        });
        while (j < model.getRowCount()) {
            //int temp = llSize.get();
            if (llSize.equals(j + 1)) {
                System.out.println(llName.getFirst());
            }

            model2.addRow(new Object[]{
                llName.getFirst()
            });
            llName.pop();
            j++;
        }
        i = 0;
        model.setNumRows(0);
    }//GEN-LAST:event_Execute1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SPF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Execute;
    private javax.swing.JButton Execute1;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName10;
    private javax.swing.JLabel lblName11;
    private javax.swing.JLabel lblName12;
    private javax.swing.JLabel lblName13;
    private javax.swing.JLabel lblName14;
    private javax.swing.JLabel lblName15;
    private javax.swing.JLabel lblName16;
    private javax.swing.JLabel lblName17;
    private javax.swing.JLabel lblName18;
    private javax.swing.JLabel lblName19;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName20;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblName9;
    private javax.swing.JLabel lblTamanio1;
    private javax.swing.JLabel lblTamanio10;
    private javax.swing.JLabel lblTamanio11;
    private javax.swing.JLabel lblTamanio12;
    private javax.swing.JLabel lblTamanio13;
    private javax.swing.JLabel lblTamanio14;
    private javax.swing.JLabel lblTamanio15;
    private javax.swing.JLabel lblTamanio16;
    private javax.swing.JLabel lblTamanio17;
    private javax.swing.JLabel lblTamanio18;
    private javax.swing.JLabel lblTamanio19;
    private javax.swing.JLabel lblTamanio2;
    private javax.swing.JLabel lblTamanio20;
    private javax.swing.JLabel lblTamanio3;
    private javax.swing.JLabel lblTamanio4;
    private javax.swing.JLabel lblTamanio5;
    private javax.swing.JLabel lblTamanio6;
    private javax.swing.JLabel lblTamanio7;
    private javax.swing.JLabel lblTamanio8;
    private javax.swing.JLabel lblTamanio9;
    private javax.swing.JTextField txtMemory;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
